services:
  cicd-agent:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./pipelines:/app/pipelines
      - ./logs:/app/logs
      - ./data:/app/data  # For data persistence
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
    environment:
      - PORT=8080
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example app service (for testing pipelines)
  # test-app:
  #   build: ../
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - cicd-agent
  #   profiles:
  #     - testing

volumes:
  pipeline_data:
  agent_logs: 
